MASSHUU12/godot-confirma

addons/confirma/docs/TESTING.md, addons/confirma/src/classes/TestClass.cs, addons/confirma/src/classes/TestExecutor.cs, addons/confirma/src/classes/TestMethod.cs, addons/confirma/src/types/TestClassResult.cs, addons/confirma/src/types/TestMethodResult.cs, addons/confirma/src/types/TestResult.cs
=> Handle `Ignore` attribute

addons/confirma/docs/TESTING.md, addons/confirma/src/classes/TestClass.cs, addons/confirma/src/helpers/Reflection.cs
=> Handle BeforeAll attribute

addons/confirma/docs/TESTING.md, addons/confirma/src/classes/TestClass.cs, addons/confirma/src/classes/TestExecutor.cs, addons/confirma/src/types/TestClassResult.cs, addons/confirma/src/types/TestResult.cs
=> Handle AfterAll attribute

addons/confirma/docs/TESTING.md, addons/confirma/src/classes/TestClass.cs
=> Handle SetUp attribute

addons/confirma/docs/TESTING.md, addons/confirma/src/classes/TestClass.cs, addons/confirma/src/types/LifecycleMethodData.cs
=> Handle TearDown attribute

.vscode/launch.json, addons/confirma/docs/ARGUMENTS.md, addons/confirma/src/classes/TestExecutor.cs, addons/confirma/src/scenes/confirma_autoload/ConfirmaAutoload.cs, addons/confirma/src/scenes/test_runner/TestRunner.cs, addons/confirma/src/scenes/test_runner_game/TestRunnerGame.cs
=> Allow testing single class

addons/confirma/src/classes/TestCase.cs, addons/confirma/src/classes/TestClass.cs, addons/confirma/src/classes/TestExecutor.cs, addons/confirma/src/classes/TestMethod.cs, addons/confirma/src/scenes/test_runner/TestRunner.cs
=> Make test execution asynchronous

.vscode/settings.json, addons/confirma/docs/TESTING.md, addons/confirma/src/attributes/ParallelizableAttribute.cs, addons/confirma/src/classes/TestCase.cs, addons/confirma/src/classes/TestClass.cs, addons/confirma/src/classes/TestExecutor.cs, addons/confirma/src/classes/TestMethod.cs, addons/confirma/src/helpers/Reflection.cs, addons/confirma/src/scenes/test_runner/TestRunner.cs, tests/ConfirmArrayTest.cs, tests/ConfirmBooleanTest.cs, tests/ConfirmEqualTest.cs, tests/ConfirmNullTest.cs, tests/ConfirmRangeTest.cs, tests/ConfirmStringTest.cs, tests/ConfirmTest.cs, tests/ConfirmTypeTest.cs
=> Add parralel execution support

CHANGELOG.md, addons/confirma/docs/ARGUMENTS.md, addons/confirma/src/classes/TestClass.cs, addons/confirma/src/classes/TestExecutor.cs, addons/confirma/src/classes/TestMethod.cs, addons/confirma/src/scenes/confirma_autoload/ConfirmaAutoload.cs, addons/confirma/src/scenes/test_runner/TestRunner.cs, addons/confirma/src/scenes/test_runner_game/TestRunnerGame.cs, addons/confirma/src/types/TestResult.cs, addons/confirma/src/types/TestsProps.cs
=> Add   `--confirma-exit-on-failure` argument

CHANGELOG.md, README.md, addons/confirma/README.md, addons/confirma/docs/ARGUMENTS.md, addons/confirma/src/classes/TestExecutor.cs, addons/confirma/src/classes/TestMethod.cs, addons/confirma/src/classes/TestOutput.cs, addons/confirma/src/enums/ETestCaseState.cs, addons/confirma/src/scenes/confirma_autoload/ConfirmaAutoload.cs, addons/confirma/src/scenes/test_bottom_panel/TestBottomPanel.cs, addons/confirma/src/scenes/test_bottom_panel/TestBottomPanel.tscn, addons/confirma/src/scenes/test_runner/TestRunner.cs, addons/confirma/src/scenes/test_runner_game/TestRunnerGame.cs, addons/confirma/src/types/TestResult.cs, addons/confirma/src/types/TestsProps.cs, tests/ConfirmSignalTest.cs
=> Simplify output and add verbose option

tests/ConfirmSignalTest.cs
=> fix: remove RID leakage

CHANGELOG.md, addons/confirma/docs/TESTING.md, addons/confirma/src/attributes/IgnoreAttribute.cs, addons/confirma/src/classes/TestExecutor.cs, addons/confirma/src/classes/TestingMethod.cs, addons/confirma/src/enums/EIgnoreMode.cs, tests/GlobalTest.cs
=> Extend Ignore attribute

CHANGELOG.md, addons/confirma/docs/TESTING.md, addons/confirma/src/extensions/ConfirmArrayExtensions.cs, addons/confirma/src/extensions/ConfirmAttributeExtensions.cs, addons/confirma/src/extensions/ConfirmBooleanExtensions.cs, addons/confirma/src/extensions/ConfirmDictionaryExtensions.cs, addons/confirma/src/extensions/ConfirmEqualExtensions.cs, addons/confirma/src/extensions/ConfirmExceptionExtensions.cs, addons/confirma/src/extensions/ConfirmFileExtensions.cs, addons/confirma/src/extensions/ConfirmIEnumerableExtensions.cs, addons/confirma/src/extensions/ConfirmNullExtensions.cs, addons/confirma/src/extensions/ConfirmNumericExtensions.cs, addons/confirma/src/extensions/ConfirmRangeExtensions.cs, addons/confirma/src/extensions/ConfirmSignalExtensions.cs, addons/confirma/src/extensions/ConfirmStringExtensions.cs, addons/confirma/src/extensions/ConfirmTypeExtensions.cs, addons/confirma/src/extensions/ConfirmUuidExtensions.cs, addons/confirma/src/extensions/ConfirmVectorExtensions.cs, tests/ChainingTest.cs
=> Allow chaining assertions

CHANGELOG.md, Confirma.csproj, addons/confirma/docs/TESTING.md, addons/confirma/src/attributes/RepeatAttribute.cs, addons/confirma/src/classes/TestCase.cs, addons/confirma/src/classes/TestDiscovery.cs, addons/confirma/src/classes/TestMethodResult.cs, addons/confirma/src/classes/TestingClass.cs, addons/confirma/src/classes/TestingMethod.cs, addons/confirma/src/types/TestMethodResult.cs, tests/RandomNumberExtensionsTest.cs, tests/RandomUuidExtensionsTest.cs, tests/RepeatAttributeTest.cs
=> Allow repeating test cases

CHANGELOG.md, addons/confirma/src/extensions/ConfirmExceptionExtensions.cs, tests/ConfirmExceptionTest.cs
=> Add ConfirmThrowsWMessage assertion

addons/confirma/docs/ARGUMENTS.md, addons/confirma/src/classes/TestingClass.cs, addons/confirma/src/classes/TestingMethod.cs, addons/confirma/src/scenes/confirma_autoload/ConfirmaAutoload.cs, addons/confirma/src/types/TestsProps.cs
- updated docs for new argument `--confirma-method`
- data parsing from argument `--confirma-method`
- throws warning and stops running if method is missing
Everything tested and works as intended.
=> feat: Run single test method 

CHANGELOG.md, addons/confirma/docs/TESTING.md, addons/confirma/src/attributes/RepeatAttribute.cs, addons/confirma/src/classes/TestCase.cs, addons/confirma/src/classes/TestingMethod.cs
=> Add flag to stop repeating test after first failure

CHANGELOG.md, addons/confirma/src/classes/TestLog.cs, addons/confirma/src/extensions/StringExtensions.cs, tests/StringExtensionsTest.cs
=> feat: remove special characters from output in args

addons/confirma/src/classes/TestLog.cs, addons/confirma/src/helpers/Colors.cs
=> feat: Display class names in different color

CHANGELOG.md, addons/confirma/src/helpers/Colors.cs, addons/confirma/src/helpers/Log.cs
=> chore: make methods in Log & Colors generic

.vscode/launch.json, CHANGELOG.md, addons/confirma/docs/ARGUMENTS.md, addons/confirma/src/scenes/confirma_autoload/ConfirmaAutoload.cs, addons/confirma/src/types/TestsProps.cs, scripts/run_tests.ps1, scripts/run_tests.sh
=> feat: remove '--confirma-quit' argument

CHANGELOG.md, addons/confirma/docs/TESTING.md, addons/confirma/src/classes/GdScriptInfo.cs, addons/confirma/src/classes/TestClass.gd, addons/confirma/src/classes/discovery/GdTestDiscovery.cs, addons/confirma/src/classes/executors/GdTestExecutor.cs, addons/confirma/src/enums/ELifecycleMethodName.cs
=> feat: implement lifecycle methods for GDScript

CHANGELOG.md, addons/confirma/docs/TESTING.md, addons/confirma/src/classes/TestClass.gd, addons/confirma/src/classes/executors/GdTestExecutor.cs
=> feat: implement category functionality for GDScript

CHANGELOG.md, addons/confirma/Plugin.cs, addons/confirma/docs/TESTING.md, addons/confirma/src/classes/Ignore.gd, addons/confirma/src/classes/TestClass.gd, addons/confirma/src/classes/executors/GdTestExecutor.cs, addons/confirma/src/types/RunTarget.gd, addons/confirma/src/types/RunTarget.tres, gdtests/wrappers/confirm_boolean_wrapper_test.gd, tests/PluginTest.cs
=> feat: implement `ignore` method for GDScript

addons/confirma/src/classes/TestLog.cs, addons/confirma/src/classes/TestingClass.cs, addons/confirma/src/classes/TestingMethod.cs, addons/confirma/src/classes/executors/CsTestExecutor.cs, addons/confirma/src/classes/executors/GdTestExecutor.cs, addons/confirma/src/enums/ELangType.cs, addons/confirma/src/helpers/Colors.cs
fixes #156 
ToDo before merging:
In editor:
(Verbose)
In console:
=> fix: #156 

tests/extensions/ConfirmEventTest.cs
new tests for:
- `eventHandler` being `null`
- `fieldInfo` being `null`
=> test: add unit tests for `GetEventName`

addons/confirma/src/exceptions/ConfirmAssertException.cs, addons/confirma/src/extensions/ConfirmEqualExtensions.cs, addons/confirma/src/helpers/AssertionMessageGenerator.cs, tests/extensions/ConfirmEqualTest.cs
=> feat: allow formatting null values in AssertionMessageGenerator

CHANGELOG.md, addons/confirma/docs/TESTING.md, addons/confirma/src/classes/TestCase.cs, addons/confirma/src/classes/TestingClass.cs, addons/confirma/src/classes/TestingMethod.cs, addons/confirma/src/helpers/TypeHelper.cs, tests/RegularTestClassTest.cs, tests/StaticTestClassTest.cs, tests/classes/TestCaseTest.cs, tests/helpers/TypeHelperTest.cs
Resolve #199
#199
#199
Unit tests were created.
None.
=> feat: add support for non-static classes

CHANGELOG.md, addons/confirma/docs/ARGUMENTS.md, addons/confirma/src/classes/TestManager.cs, addons/confirma/src/classes/TestingClass.cs, addons/confirma/src/classes/executors/CsTestExecutor.cs, addons/confirma/src/scenes/confirma_autoload/ConfirmaAutoload.cs, addons/confirma/src/types/TestsProps.cs, e2e/tests/confirma_verbose.test.ts, e2e/tests/orphans_monitor_tests/OrphansMonitorTest.cs, e2e/tests/orphans_monitor_tests/orphans_monitor.test.ts
Finished basic orphan monitor, so it is no longer considered experimental.
Without it, this functionality would not be ready.
None.
E2E tests have been added.
None.
=> Finish basic orphan monitor

CHANGELOG.md, addons/confirma/src/scenes/confirma_bottom_panel_options/ConfirmaBotomPanelOptions.cs, addons/confirma/src/scenes/confirma_bottom_panel_options/confirmaBotomPanelOptions.tscn
[Insert brief description of the changes made]
[Insert explanation of the reason behind the change]
[Insert issue numbers or links to related issues, if any]
[Insert information about the testing process, e.g. unit tests, E2E tests, manual testing, etc.]
[Insert information about any known issues or edge cases]
=> feat: add switch in editor for orphans monitor

CHANGELOG.md, addons/confirma/src/scenes/confirma_bottom_panel_options/ConfirmaBottomPanelOptions.cs
[Insert brief description of the changes made]
[Insert explanation of the reason behind the change]
[Insert issue numbers or links to related issues, if any]
[Insert information about the testing process, e.g. unit tests, E2E tests, manual testing, etc.]
[Insert information about any known issues or edge cases]
=> feat: allow overriding output path via bottom panel

CHANGELOG.md, addons/confirma/docs/TESTING.md, script_templates/Node/Test.cs, script_templates/Node/TestFull.cs, script_templates/Node/test.gd, script_templates/Node/test_full.gd
[Insert brief description of the changes made]
[Insert explanation of the reason behind the change]
[Insert issue numbers or links to related issues, if any]
[Insert information about the testing process, e.g. unit tests, E2E tests, manual testing, etc.]
[Insert information about any known issues or edge cases]
=> feat: create script templates

CHANGELOG.md, addons/confirma/src/extensions/ConfirmTypeExtensions.cs, tests/extensions/ConfirmTypeTest.cs, tests/formatters/AutomaticFormatterTest.cs
=> feat: add ConfirmInstanceOf & ConfirmNotInstanceOf assertions

CHANGELOG.md, Confirma.csproj, addons/confirma/docs/TESTING.md, addons/confirma/src/attributes/RepeatAttribute.cs, addons/confirma/src/classes/TestingMethod.cs, tests/FlakyTestTest.cs
Adds ability to handle [flaky tests](https://www.lambdatest.com/learning-hub/flaky-test).
Flaky tests can be a major hurdle in the software development process.
N/A
- manual testing
- unit testing
None.
=> feat: handle flaky tests

CHANGELOG.md, addons/confirma/src/extensions/ConfirmIEnumerableExtensions.cs, tests/extensions/ConfirmIEnumerableTest.cs
=> feat: add overload for ConfirmElementsAreOrdered

CHANGELOG.md, addons/confirma/docs/TESTING.md, addons/confirma/src/attributes/IgnoreAttribute.cs, addons/confirma/src/enums/EIgnoreMode.cs, tests/attributes/IgnoreAttributeTest.cs
Adds the ability to ignore tests in headless mode.
The Ignore attribute does not have the ability to ignore tests in headless mode.
Fix #232
- unit testing
- manual testing
None.
=> feat: allow ignoring tests in headless mode

CHANGELOG.md, addons/confirma/src/extensions/ConfirmEqualExtensions.cs, tests/extensions/ConfirmEqualTest.cs, tests/trees/RadixNodeTests.cs
=> feat: add assertion for default values

CHANGELOG.md, addons/confirma/src/enums/EStringSimilarityMethod.cs, addons/confirma/src/extensions/ConfirmStringExtensions.cs, addons/confirma/src/extensions/StringExtensions.cs, tests/extensions/ConfirmStringTest.cs, tests/extensions/StringExtensionsTest.cs
#242
Fix #242
- manual testing
- unit testing
=> feat: add string similarity assertions
